const STORAGE_KEY = 'apg_divulgacao_etapa1_v1';
const initialState = {
  settings:{site:'https://antes-do-primeiro-gole.rafaeel096.chatgpt.site',book:'https://loja.uiclap.com/titulo/ua189638/',instagram:'@antesdoprimeirogole1',email:'antesdoprimeirogole1@gmail.com',whatsapp:'+55 62 99102-1154'},
  quotes:[
    {id:1,type:'livro',text:'O álcool não chegou parecendo problema. Chegou parecendo solução.'},
    {id:2,type:'livro',text:'Quase ninguém se torna dependente porque procura destruição. A maioria procura alívio.'},
    {id:3,type:'livro',text:'O primeiro gole real quase sempre começa antes da boca.'},
    {id:4,type:'livro',text:'A recaída raramente chega batendo na porta. Ela entra disfarçada.'},
    {id:5,type:'livro',text:'Permanecer também é um verbo de resistência.'},
    {id:6,type:'cartilha',text:'Pensamento de beber não é ordem. É sinal de alerta.'},
    {id:7,type:'cartilha',text:'O sinal que você esconde pode virar recaída. O sinal que você fala pode virar cuidado.'},
    {id:8,type:'cartilha',text:'Hoje eu não preciso vencer a vida inteira. Preciso atravessar este dia.'},
    {id:9,type:'cartilha',text:'Recaída não é o fim. O fim é desistir do cuidado.'},
    {id:10,type:'cartilha',text:'Hoje continuo aqui. E isso já é um começo.'},
    {id:11,type:'cta',text:'Talvez alguém próximo precise encontrar estas palavras. Compartilhe com cuidado.'},
    {id:12,type:'cta',text:'Acompanhe o projeto para continuar esta conversa sobre cuidado, recomeço e saúde mental.'}
  ],
  schedule:[
    {id:1,date:futureDate(1),channel:'Instagram',format:'Post',title:'Frase do livro — solução que vira problema',status:'planejado'},
    {id:2,date:futureDate(3),channel:'Instagram/Facebook',format:'Carrossel',title:'Pensamento de beber não é ordem',status:'planejado'},
    {id:3,date:futureDate(5),channel:'Instagram',format:'Reel',title:'Experiência vivida: o que acontece antes do primeiro gole',status:'rascunho'},
    {id:4,date:futureDate(7),channel:'E-mail',format:'Prospecção',title:'Primeira rodada com universidades',status:'planejado'}
  ],
  prospects:[
    {id:1,institution:'PUC Goiás — Programa em Nome da Vida',segment:'Universidade / prevenção',priority:96,status:'Preparar contato',next:'Apresentar experiência vivida e propor roda reflexiva'},
    {id:2,institution:'UNIALFA — Psicologia',segment:'Universidade / Psicologia',priority:95,status:'Preparar contato',next:'Coordenação, extensão ou núcleo de práticas'},
    {id:3,institution:'UFG — Psicologia e extensão',segment:'Universidade pública',priority:94,status:'Preparar contato',next:'Propor aula aberta ou atividade de extensão'},
    {id:4,institution:'AA — Área 09 Goiás',segment:'Ajuda mútua',priority:92,status:'Pesquisar canal',next:'Informação ao Público / cooperação profissional'},
    {id:5,institution:'NA — Goiás',segment:'Ajuda mútua',priority:90,status:'Pesquisar canal',next:'Pedir orientação institucional para atividade aberta'},
    {id:6,institution:'Fórum Goiano de Saúde Mental',segment:'Luta antimanicomial',priority:88,status:'Pesquisar contato',next:'Apresentar protagonismo do usuário e cuidado em liberdade'},
    {id:7,institution:'CRP-09',segment:'Conselho profissional',priority:84,status:'Pesquisar comissão',next:'Solicitar canal para diálogo educativo'},
    {id:8,institution:'Associação Psiquiátrica de Goiás',segment:'Associação profissional',priority:82,status:'Pesquisar eventos',next:'Apresentar como narrativa de experiência vivida'}
  ],
  drafts:[], approvals:[], metrics:[{id:1,week:'Semana inicial',followers:0,shares:0,saves:0,replies:0,invites:0}]
};
function futureDate(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
let state=loadState(); let currentDraft=''; let activeFilter='all';
const titles={dashboard:'Visão geral',calendar:'Calendário',creator:'Criar conteúdo',library:'Biblioteca',prospects:'Prospecção',approvals:'Aprovações',metrics:'Métricas',settings:'Configurações'};
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(initialState)}catch{return structuredClone(initialState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}
function el(id){return document.getElementById(id)}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatDate(v){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v+'T12:00:00'))}
function showToast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function navigate(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));el('viewTitle').textContent=titles[view];el('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderDashboard();renderCalendar();renderQuoteSelect();renderLibrary();renderProspects();renderApprovals();renderMetrics();renderSettings()}
function renderDashboard(){
 const planned=state.schedule.filter(x=>x.status!=='publicado').length, pending=state.approvals.filter(x=>x.status==='pendente').length, priority=state.prospects.filter(x=>x.priority>=90).length, last=state.metrics[state.metrics.length-1]||{};
 el('statsGrid').innerHTML=[['Conteúdos planejados',planned],['Aguardando aprovação',pending],['Contatos prioritários',priority],['Novos seguidores',last.followers||0]].map(([l,v])=>`<div class="stat-card"><span>${l}</span><strong>${v}</strong><span>controle local</span></div>`).join('');
 const next=[...state.schedule].sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4); el('upcomingList').innerHTML=next.length?next.map(x=>`<div class="list-row"><div><strong>${escapeHtml(x.title)}</strong><span>${formatDate(x.date)} · ${escapeHtml(x.channel)}</span></div><span class="badge">${escapeHtml(x.format)}</span></div>`).join(''):'<div class="empty">Nenhum item planejado.</div>';
 const pp=[...state.prospects].sort((a,b)=>b.priority-a.priority).slice(0,4); el('priorityProspects').innerHTML=pp.map(x=>`<div class="list-row"><div><strong>${escapeHtml(x.institution)}</strong><span>${escapeHtml(x.next)}</span></div><span class="badge">${x.priority}</span></div>`).join('');
}
function renderCalendar(){const rows=[...state.schedule].sort((a,b)=>a.date.localeCompare(b.date));el('calendarList').innerHTML=rows.length?rows.map(x=>`<div class="calendar-item"><div class="date-box"><strong>${new Date(x.date+'T12:00:00').getDate()}</strong><span>${new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(x.date+'T12:00:00'))}</span></div><div><h4>${escapeHtml(x.title)}</h4><p>${escapeHtml(x.channel)} · ${escapeHtml(x.format)}</p></div><span class="status ${x.status==='rascunho'?'draft':'pending'}">${escapeHtml(x.status)}</span></div>`).join(''):'<div class="empty">Calendário vazio.</div>'}
function renderQuoteSelect(){el('quoteSelect').innerHTML=state.quotes.filter(x=>x.type!=='cta').map(q=>`<option value="${q.id}">${escapeHtml(q.text)}</option>`).join('')}
function renderLibrary(){const items=state.quotes.filter(q=>activeFilter==='all'||q.type===activeFilter);el('libraryGrid').innerHTML=items.map(q=>`<article class="quote-card"><span class="eyebrow">${q.type.toUpperCase()}</span><blockquote>“${escapeHtml(q.text)}”</blockquote><footer><span>ID ${q.id}</span><button class="text-button" data-copy-quote="${q.id}">Copiar</button></footer></article>`).join('')||'<div class="empty">Nenhuma frase nesta categoria.</div>'}
function renderProspects(){el('prospectTable').innerHTML=[...state.prospects].sort((a,b)=>b.priority-a.priority).map(p=>`<tr><td><strong>${escapeHtml(p.institution)}</strong></td><td>${escapeHtml(p.segment)}</td><td class="priority">${p.priority}</td><td><span class="status pending">${escapeHtml(p.status)}</span></td><td>${escapeHtml(p.next)}</td><td><button class="text-button" data-prospect="${p.id}">Mensagem</button></td></tr>`).join('')}
function renderApprovals(){el('approvalList').innerHTML=state.approvals.length?state.approvals.map(a=>`<article class="approval-card"><div class="card-header"><div><span class="eyebrow">${escapeHtml(a.format||'CONTEÚDO')}</span><h3>${escapeHtml(a.audience||'Público')}</h3></div><span class="status ${a.status==='aprovado'?'approved':'pending'}">${escapeHtml(a.status)}</span></div><p>${escapeHtml(a.text)}</p><div class="button-row"><button class="secondary" data-copy-approval="${a.id}">Copiar</button>${a.status!=='aprovado'?`<button class="primary" data-approve="${a.id}">Aprovar</button>`:''}</div></article>`).join(''):'<div class="card empty">Nenhum conteúdo aguardando aprovação.</div>'}
function renderMetrics(){const totals=state.metrics.reduce((a,m)=>({followers:a.followers+(+m.followers||0),shares:a.shares+(+m.shares||0),saves:a.saves+(+m.saves||0),invites:a.invites+(+m.invites||0)}),{followers:0,shares:0,saves:0,invites:0});el('metricSummary').innerHTML=[['Seguidores',totals.followers],['Compartilhamentos',totals.shares],['Salvamentos',totals.saves],['Convites',totals.invites]].map(([l,v])=>`<div class="stat-card"><span>${l}</span><strong>${v}</strong><span>acumulado informado</span></div>`).join('');el('metricTable').innerHTML=state.metrics.map(m=>`<tr><td>${escapeHtml(m.week)}</td><td>${m.followers}</td><td>${m.shares}</td><td>${m.saves}</td><td>${m.replies}</td><td>${m.invites}</td></tr>`).join('')}
function renderSettings(){el('siteSetting').value=state.settings.site;el('bookSetting').value=state.settings.book;el('instagramSetting').value=state.settings.instagram;el('emailSetting').value=state.settings.email;el('whatsappSetting').value=state.settings.whatsapp}
function buildDraft(){const audience=el('audience').value,format=el('format').value,objective=el('objective').value,quote=state.quotes.find(q=>q.id===+el('quoteSelect').value)?.text||'',ctx=el('contextInput').value.trim();const intro={geral:'Nem todo sofrimento aparece por fora.',empresa:'O projeto Antes do Primeiro Gole transforma experiência vivida em literatura, educação e diálogo responsável.',universidade:'A teoria é essencial, mas a experiência vivida ajuda a compreender o que acontece por dentro da dependência.',saude:'Este conteúdo não substitui cuidado profissional: ele coloca a experiência do usuário em diálogo com a rede.',grupos:'Com respeito à autonomia e ao anonimato, esta é uma reflexão independente sobre dependência, recaída e pedido de ajuda.'}[audience];const body={seguir:'Acompanhe o perfil para continuar esta conversa e compartilhe com cuidado, sem expor ninguém.',cartilha:`A cartilha digital é gratuita e pode ser acessada pelo site principal: ${state.settings.site}`,livro:`O livro completo está disponível em versão impressa para compra pela UICLAP: ${state.settings.book}`,impressao:'Buscamos parceiros para imprimir a cartilha com qualidade e distribuí-la gratuitamente em ações, serviços e instituições.',roda:'O projeto está aberto a convites para rodas de conversa e atividades educativas, sempre em diálogo com a instituição.'}[objective];const formatLead={post:'',carrossel:'CARROSSEL\n1. A frase\n2. O que ela revela\n3. O que pode virar cuidado\n4. Onde buscar diálogo\n\n',reel:'ROTEIRO DE REEL\nCena 1 — Rafael em plano próximo\nFala: ',story:'STORIES\nTela 1: ',mensagem:'Olá! Meu nome é Rafael Leandro de Carvalho. '}[format];currentDraft=`${formatLead}${intro}\n\n“${quote}”\n\n${ctx?ctx+'\n\n':''}${body}\n\n${state.settings.instagram} · ${state.settings.site}`;el('previewArt').innerHTML=`<blockquote>“${escapeHtml(quote)}”</blockquote>`;el('previewCaption').textContent=currentDraft;return {audience,format,text:currentDraft}}
function openDialog(type){const d=el('genericDialog'),fields=el('dialogFields'),title=el('dialogTitle');d.dataset.type=type;if(type==='schedule'){title.textContent='Adicionar ao calendário';fields.innerHTML=field('date','Data','date',futureDate(1))+field('title','Título','text','')+field('channel','Canal','text','Instagram')+field('format2','Formato','text','Post')}if(type==='quote'){title.textContent='Adicionar frase';fields.innerHTML=selectField('quoteType','Categoria',[['livro','Livro'],['cartilha','Cartilha'],['cta','Chamada']])+textAreaField('quoteText','Frase')}if(type==='prospect'){title.textContent='Adicionar contato';fields.innerHTML=field('institution','Instituição','text','')+field('segment','Segmento','text','')+field('priority','Prioridade (0 a 100)','number','80')+field('status','Status','text','Pesquisar')+textAreaField('next','Próxima ação')}if(type==='metric'){title.textContent='Registrar métricas';fields.innerHTML=field('week','Semana','text','Semana de '+new Intl.DateTimeFormat('pt-BR').format(new Date()))+field('followers','Novos seguidores','number','0')+field('shares','Compartilhamentos','number','0')+field('saves','Salvamentos','number','0')+field('replies','Respostas','number','0')+field('invites','Convites','number','0')}d.showModal()}
function field(id,label,type,value){return `<label class="dialog-field">${label}<input id="${id}" type="${type}" value="${escapeHtml(value)}" required></label>`}
function textAreaField(id,label){return `<label class="dialog-field">${label}<textarea id="${id}" rows="4" required></textarea></label>`}
function selectField(id,label,opts){return `<label class="dialog-field">${label}<select id="${id}">${opts.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>`}
function saveDialog(){const type=el('genericDialog').dataset.type;if(type==='schedule')state.schedule.push({id:Date.now(),date:el('date').value,title:el('title').value,channel:el('channel').value,format:el('format2').value,status:'planejado'});if(type==='quote')state.quotes.push({id:Date.now(),type:el('quoteType').value,text:el('quoteText').value});if(type==='prospect')state.prospects.push({id:Date.now(),institution:el('institution').value,segment:el('segment').value,priority:+el('priority').value,status:el('status').value,next:el('next').value});if(type==='metric')state.metrics.push({id:Date.now(),week:el('week').value,followers:+el('followers').value,shares:+el('shares').value,saves:+el('saves').value,replies:+el('replies').value,invites:+el('invites').value});saveState();showToast('Item salvo.')}
function generateProspectMessage(p){return `Olá! Sou Rafael Leandro de Carvalho, autor do projeto Antes do Primeiro Gole, construído a partir de uma experiência vivida durante anos com dependência do álcool, recaídas, tratamento, CAPS e reconstrução. Acredito que este relato pode contribuir para aproximar o conhecimento técnico e institucional da realidade de quem viveu o vício por dentro.\n\nGostaria de apresentar o projeto à ${p.institution} e conversar sobre: ${p.next}.\n\nO projeto reúne livro impresso, cartilha digital gratuita e proposta de impressão física para distribuição gratuita, além de rodas de conversa.\n\nSite: ${state.settings.site}\nInstagram: ${state.settings.instagram}`}
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast('Texto copiado.')}catch{showToast('Não foi possível copiar automaticamente.')}}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='backup-divulgacao-antes-do-primeiro-gole.json';a.click();URL.revokeObjectURL(url);showToast('Backup exportado.')}

document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)navigate(go.dataset.go);const nav=e.target.closest('.nav-item');if(nav)navigate(nav.dataset.view);const cq=e.target.closest('[data-copy-quote]');if(cq)copyText(state.quotes.find(q=>q.id===+cq.dataset.copyQuote).text);const cp=e.target.closest('[data-prospect]');if(cp){const p=state.prospects.find(x=>x.id===+cp.dataset.prospect);copyText(generateProspectMessage(p))}const ca=e.target.closest('[data-copy-approval]');if(ca)copyText(state.approvals.find(x=>x.id===+ca.dataset.copyApproval).text);const ap=e.target.closest('[data-approve]');if(ap){state.approvals.find(x=>x.id===+ap.dataset.approve).status='aprovado';saveState();showToast('Conteúdo aprovado.')}})
document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');activeFilter=c.dataset.filter;renderLibrary()}));
el('contentForm').addEventListener('submit',e=>{e.preventDefault();buildDraft();showToast('Rascunho gerado.')});el('copyDraftButton').onclick=()=>copyText(currentDraft||el('previewCaption').textContent);el('saveDraftButton').onclick=()=>{if(!currentDraft)return showToast('Gere um rascunho primeiro.');state.drafts.push({id:Date.now(),text:currentDraft,created:new Date().toISOString()});saveState();showToast('Rascunho salvo.')};el('sendApprovalButton').onclick=()=>{if(!currentDraft)return showToast('Gere um rascunho primeiro.');state.approvals.unshift({id:Date.now(),text:currentDraft,audience:el('audience').selectedOptions[0].text,format:el('format').selectedOptions[0].text,status:'pendente'});saveState();navigate('approvals');showToast('Enviado para aprovação.')};
el('addScheduleButton').onclick=()=>openDialog('schedule');el('addQuoteButton').onclick=()=>openDialog('quote');el('addProspectButton').onclick=()=>openDialog('prospect');el('addMetricButton').onclick=()=>openDialog('metric');el('dialogSaveButton').addEventListener('click',e=>{e.preventDefault();if(el('dialogForm').reportValidity()){saveDialog();el('genericDialog').close()}});
el('saveSettingsButton').onclick=()=>{state.settings={site:el('siteSetting').value,book:el('bookSetting').value,instagram:el('instagramSetting').value,email:el('emailSetting').value,whatsapp:el('whatsappSetting').value};saveState();showToast('Configurações salvas.')};el('exportButton').onclick=exportBackup;el('importButton').onclick=()=>el('importFile').click();el('importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);saveState();showToast('Backup importado.')}catch{showToast('Arquivo de backup inválido.')}};r.readAsText(f)});el('resetButton').onclick=()=>{if(confirm('Restaurar os dados iniciais? O conteúdo local será substituído.')){state=structuredClone(initialState);saveState();showToast('Dados restaurados.')}};el('menuButton').onclick=()=>el('sidebar').classList.toggle('open');
el('todayLabel').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
renderAll();
